const doctors = [
  { 
    id: 1, 
    name: "Dilgam Mammadov", 
    speciality: "Internal Medicine", 
    experience: "15+ Years of Experience", 
    image: "https://images.unsplash.com/photo-1580281658626-ee379f3cce93?w=500&auto=format&fit=crop&q=60", 
    rating: 4.5,
    location: "123 Main Street, Anytown USA",
    phone: "+0000000000000000",
    email: "dilgam@example.com",
    availability: "Mon-Fri 9:00-17:00",
    bio: "Dr. Dilgam Mammadov is a skilled internal medicine practitioner with over 15 years of experience. She specializes in treating a variety of medical conditions and is dedicated to providing compassionate care to her patients." ,
    Charges: "30"
  },
  { 
    id: 2, 
    name: "Ayesha Khan", 
    speciality: "Cardiologist", 
    experience: "10 Years of Experience", 
    image: "https://plus.unsplash.com/premium_photo-1661766743908-ca87957f4bb2?w=500", 
    rating: 4.7,
    location: "456 Oak Avenue, Anytown USA",
    phone: "+0000000000000000",
    email: "ayesha@example.com",
    availability: "Tue-Sat 10:00-18:00",
    bio: "Dr. Ayesha Khan is a highly skilled cardiologist with 10 years of experience. She specializes in diagnosing and treating a variety of heart conditions and is committed to providing compassionate care to her patients.",
    Charges: "50" 
  },
  { 
    id: 3, 
    name: "Farhan Ahmed", 
    speciality: "Orthopedic Surgeon", 
    experience: "8 Years of Experience", 
    image: "https://plus.unsplash.com/premium_photo-1681966945670-fc90dbc58631?w=500", 
    rating: 4.2 ,
    location: "789 Elm Street, Anytown USA",
    phone: "+0000000000000000",
    email: "farhan@example.com",
    availability: "Mon-Fri 8:00-16:00",
    bio: "Dr. Farhan Ahmed is a skilled orthopedic surgeon with 8 years of experience. He specializes in treating musculoskeletal conditions and is dedicated to providing compassionate care to his patients.",
    Charges: "40"
  },
  { 
    id: 4, 
    name: "Zainab Ali", 
    speciality: "Pediatrician", 
    experience: "5 Years of Experience", 
    image: "https://plus.unsplash.com/premium_photo-1673953510160-6d722ad05912?w=500", 
    rating: 4.8 ,
    location: "987 Pine Road, Anytown USA",
    phone: "+0000000000000000",
    email: "zainab@example.com",
    availability: "Tue-Sat 9:00-15:00",
    bio: "Dr. Zainab Ali is a skilled pediatrician with 5 years of experience. She specializes in treating childhood diseases and is dedicated to providing compassionate care to her patients.",
    Charges: "35"
  },
  { 
    id: 5, 
    name: "Omer Bashir", 
    speciality: "General Practitioner", 
    experience: "20+ Years of Experience", 
    image: "https://plus.unsplash.com/premium_photo-1723514536306-26fe5c4adeb7?w=500", 
    rating: 4.6 ,
    location: "654 Cedar Lane, Anytown USA",
    phone: "+0000000000000000",
    email: "omer@example.com",
    availability: "Mon-Fri 10:00-18:00",
    bio: "Dr. Omer Bashir is a skilled general practitioner with over 20 years of experience. He specializes in treating a variety of medical conditions and is dedicated to providing compassionate care to his patients.",
    Charges: "45"
  },
  { 
    id: 6, 
    name: "Sara Iqbal", 
    speciality: "Dermatologist", 
    experience: "12 Years of Experience", 
    image: "https://plus.unsplash.com/premium_photo-1681966531074-0957dc900a5f?w=500", 
    rating: 4.3,
    location: "321 Maple Drive, Anytown USA",
    phone: "+0000000000000000",
    email: "sara@example.com",
    availability: "Tue-Sat 11:00-17:00",
    bio: "Dr. Sara Iqbal is a skilled dermatologist with 12 years of experience. She specializes in treating skin conditions and is dedicated to providing compassionate care to her patients.",
    Charges: "38"
  },
  { 
    id: 7, 
    name: "Khalid Javed", 
    speciality: "Neurosurgeon", 
    experience: "18 Years of Experience", 
    image: "https://plus.unsplash.com/premium_photo-1661766569022-1b7f918ac3f3?w=500", 
    rating: 4.9,
    location: "876 Birch Street, Anytown USA",
    phone: "+0000000000000000",
    email: "khalid@example.com",
    availability: "Mon-Fri 9:00-16:00",
    bio: "Dr. Khalid Javed is a skilled neurosurgeon with 18 years of experience. He specializes in treating neurological conditions and is dedicated to providing compassionate care to his patients.",
    Charges: "48" 
  },
  { 
    id: 8, 
    name: "Nida Shah", 
    speciality: "Gynecologist", 
    experience: "7 Years of Experience", 
    image: "https://plus.unsplash.com/premium_photo-1681996428751-93e0294fe98d?w=500", 
    rating: 4.4,
    location: "543 Pine Road, Anytown USA",
    phone: "+0000000000000000",
    email: "nida@example.com",
    availability: "Tue-Sat 10:00-16:00",
    bio: "Dr. Nida Shah is a skilled gynecologist with 7 years of experience. She specializes in treating reproductive conditions and is dedicated to providing compassionate care to her patients.",
    Charges: "42" 
  },
];

export default doctors;
